### ISSUE TITLE
Split frame causes active modeline to "hide" middle part

### ISSUE THREAD

**Issue by publicimageltd** [domtronn/spaceline-all-the-icons.el#46] opened 2017-06-08 13:04 UTC
When I am splitting the frame (i.e. C-x 3), the active modeline (on the right) looks like this:

![emacs-modeline](https://user-images.githubusercontent.com/20790649/26929874-92475f0e-4c5b-11e7-9174-a4a015b0d9d2.png)

So the name part and the major modes get lost. Actually it looks like an involuntary application of the behavior for the inactive modeline on the left side.

**Comment by domtronn** [comment] 2017-06-08 16:14
Yes, I'm aware of this, unfortunately it's a regression/change in [Spaceline](https://github.com/TheBB/spaceline/commit/153ce1310e8eb808e3714a611c69c303b8117ab5) 😞 They've added a feature to make the mode line _"responsive"_, so that as you split your windows, the spaceline segments will be hidden if they overflow.

Personally, I dislike this feature as it lends itself hiding useful information more often than is necessary! I've raised TheBB/spaceline#146 to discuss the feature and try and work with the guys maintaining it to come up with a solution, but I don't have much time at the moment. I'd like to be able to optionally enable/disable this feature rather than have it only work this way...

They've also added in a _priority_ feature which lets you define which segments should be hidden over others but it still results in hiding a lot of the mode line 😕 But that could improve things for people!

**Comment by jwintz** [comment] 2017-06-22 20:16
That is **not** indeed related to `spaceline-all-the-icons`.

However, I think that, `projectile-current-root` or `vc-current-branch` and `flycheck-issues` are in the same segment.

Should the modeline be responsive, it would be great to keep the current git branch shown even if there is no space left to show flycheck results.

**Comment by jwintz** [comment] 2017-08-16 11:03
Here is a dirty quick fix: in `spaceline-all-the-icons-segments.el`, comment line 1017 and don't forget to add an extra closing parenthesis.

Apparently, it is caused by the rightmost segment, i.e., the clock, which adds extra space, and then, it overflows.

I'll dig more into it.

![screen shot 2017-08-16 at 13 02 11](https://user-images.githubusercontent.com/3277054/29360449-39308f04-8283-11e7-8288-8190e0f24782.png)

**Comment by jwintz** [comment] 2017-08-16 18:11
Actually, keep the line and change the width to 1 gives the expected rendering without the overflow.

**Closed** 2017-08-23 08:13 UTC
Labels: known, rendering
